//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalBusinessService.Client.InternationalBusinessService_Client_1_0 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InternationalBusinessService_Client_1_0.IInternationalBusinessService")]
    public interface IInternationalBusinessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternationalBusinessService/GetRates", ReplyAction="http://tempuri.org/IInternationalBusinessService/GetRatesResponse")]
        InternationalBusinessDTOs.Rates[] GetRates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternationalBusinessService/GetRates", ReplyAction="http://tempuri.org/IInternationalBusinessService/GetRatesResponse")]
        System.Threading.Tasks.Task<InternationalBusinessDTOs.Rates[]> GetRatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternationalBusinessService/GetTransactions", ReplyAction="http://tempuri.org/IInternationalBusinessService/GetTransactionsResponse")]
        InternationalBusinessDTOs.Transaction[] GetTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternationalBusinessService/GetTransactions", ReplyAction="http://tempuri.org/IInternationalBusinessService/GetTransactionsResponse")]
        System.Threading.Tasks.Task<InternationalBusinessDTOs.Transaction[]> GetTransactionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternationalBusinessService/GetTransactionsBySku", ReplyAction="http://tempuri.org/IInternationalBusinessService/GetTransactionsBySkuResponse")]
        InternationalBusinessDTOs.Transaction[] GetTransactionsBySku(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternationalBusinessService/GetTransactionsBySku", ReplyAction="http://tempuri.org/IInternationalBusinessService/GetTransactionsBySkuResponse")]
        System.Threading.Tasks.Task<InternationalBusinessDTOs.Transaction[]> GetTransactionsBySkuAsync(string sku);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInternationalBusinessServiceChannel : InternationalBusinessService.Client.InternationalBusinessService_Client_1_0.IInternationalBusinessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InternationalBusinessServiceClient : System.ServiceModel.ClientBase<InternationalBusinessService.Client.InternationalBusinessService_Client_1_0.IInternationalBusinessService>, InternationalBusinessService.Client.InternationalBusinessService_Client_1_0.IInternationalBusinessService {
        
        public InternationalBusinessServiceClient() {
        }
        
        public InternationalBusinessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InternationalBusinessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternationalBusinessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternationalBusinessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InternationalBusinessDTOs.Rates[] GetRates() {
            return base.Channel.GetRates();
        }
        
        public System.Threading.Tasks.Task<InternationalBusinessDTOs.Rates[]> GetRatesAsync() {
            return base.Channel.GetRatesAsync();
        }
        
        public InternationalBusinessDTOs.Transaction[] GetTransactions() {
            return base.Channel.GetTransactions();
        }
        
        public System.Threading.Tasks.Task<InternationalBusinessDTOs.Transaction[]> GetTransactionsAsync() {
            return base.Channel.GetTransactionsAsync();
        }
        
        public InternationalBusinessDTOs.Transaction[] GetTransactionsBySku(string sku) {
            return base.Channel.GetTransactionsBySku(sku);
        }
        
        public System.Threading.Tasks.Task<InternationalBusinessDTOs.Transaction[]> GetTransactionsBySkuAsync(string sku) {
            return base.Channel.GetTransactionsBySkuAsync(sku);
        }
    }
}
